(*
   $Id: mim.exp,v 1.1 2011/12/30 00:23:43 raira Exp $
   N - ISO/CD-TS - 10303- kinematic_motion_representation - EXPRESS MIM*)

SCHEMA Kinematic_motion_representation_mim;

USE FROM Kinematic_state_mim;
USE FROM B_spline_geometry_mim; --  ISO/TS 10303-1801
USE FROM Geometric_model_relationship_mim; -- ISO/TS 10303-1403
USE FROM Parametric_representation_mim;
USE FROM Contextual_shape_positioning_mim; -- ISO/TS 10303-1027
USE FROM kinematic_motion_representation_schema;

END_SCHEMA;
