(*
   $Id: arm.exp,v 1.1 2011/12/30 00:23:57 raira Exp $
   N - ISO/CD-TS - 10303- identification_relationship - EXPRESS ARM*)


SCHEMA Identification_relationship_arm;

USE FROM Identification_assignment_arm;

ENTITY Identification_relationship;
  relating_identification_assignment : Identification_assignment;
  related_identification_assignment : Identification_assignment;
END_ENTITY;

END_SCHEMA;

